<section>
<div class="container"; style="margin-top: 100px">

<h3>Condiciones generales de uso</h3>

<p>Le rogamos lea las siguientes condiciones generales de uso (las “Condiciones Generales”) que rigen la utilización del “Sitio Web” ubicado en <a href="http://www.rolandiberia.com/">http://www.rolandiberia.com</a> y el acceso al mismo; incluyendo, a título meramente enunciativo y no limitativo, el acceso a los tableros de mensajes (en lo sucesivo, el “Servicio”) y la relación establecida entre usted y Roland Corporation, sus sociedades subsidiarias y filiales y toda persona física o jurídica vinculada a este Sitio Web (en lo sucesivo, y en su conjunto, “Roland” o “Nosotros”). Al hacer uso de este Servicio usted acepta y se compromete a observar las presentes Condiciones Generales. Los derechos que se otorgan al Usuario en virtud de las mismas son de naturaleza personal, no exclusiva, intransferible y revocable, estando su ejercicio limitado al Usuario de que se trate. En caso de que no acepte estas Condiciones Generales, deberá abstenerse de hacer uso del Servicio.</p>
<p>Nos reservamos el derecho a introducir en las Condiciones Generales las modificaciones que estimemos oportunas, en cualquier momento y sin notificárselo a usted previamente, mediante la publicación en este sitio Web de dichas modificaciones. Al hacer uso del Servicio tras la introducción de modificaciones a las presentes Condiciones Generales, usted acepta quedar vinculado por las modificaciones introducidas en ellas.</p>
<p>Si usted carece de la capacidad legal necesaria para prestar su consentimiento al acuerdo que surge de estas Condiciones Generales, no podrá hacer uso de los Servicios en tanto Roland no reciba el consentimiento de sus padres o de su tutor legal.</p>

<hr />

<h4>Exclusión de garantías:</h4>
<p>Al hacer uso del Servicio, así como de cualquier software o contenido comprendido en él, usted acepta la responsabilidad exclusiva por dicho uso. El Servicio se le proporciona como medio para facilitar la transmisión de información y el debate sobre productos Roland y recursos relacionados con ellos, si bien Nosotros no garantizamos que la información facilitada sea exacta ni completa. EL SERVICIO SE SUMINISTRA SOBRE UNA BASE “TAL COMO ESTÁ”, SIN INCLUIR GARANTÍAS TÁCITAS O EXPRESAS DE NINGUNA CLASE; ENTRE ELLAS, A TÍTULO MERAMENTE ENUNCIATIVO, CUALQUIER GARANTÍA RELATIVA A INFORMACIÓN, DATOS, SOFTWARE, HERRAMIENTAS, SERVICIOS O ACCESO ININTERRUMPIDO. CONCRETAMENTE, EL SERVICIO SE HALLA EXCLUIDO DE TODAS Y CUALESQUIERA GARANTÍAS; ENTRE ELLAS, A TÍTULO MERAMENTE ENUNCIATIVO: (i) GARANTÍAS RELATIVAS A LA DISPONIBILIDAD, FIABILIDAD, EXACTITUD, UTILIDAD, CONTENIDO, OPORTUNIDAD O SEGURIDAD DE LA INFORMACIÓN O LOS SERVICIOS, Y (ii) GARANTÍAS SOBRE EL TÍTULO, GARANTÍAS DE NO VULNERAR DERECHOS DE TERCEROS Y GARANTÍAS DE COMERCIABILIDAD O IDONEIDAD PARA UN FIN DETERMINADO. ESTA EXCLUSIÓN DE RESPONSABILIDAD SE EXTIENDE A TODOS LOS DAÑOS O LESIONES CAUSADOS POR CUALQUIER FALLO EN EL FUNCIONAMIENTO, ERROR, OMISIÓN, INTERRUPCIÓN, BORRADO, DEFECTO, DEMORA EN EL FUNCIONAMIENTO O EN LA TRANSMISIÓN, VIRUS INFORMÁTICO, INTERRUPCIÓN DE LA COMUNICACIÓN, ROBO O DESTRUCCIÓN, ASÍ COMO AL USO O ALTERACIÓN DEL REGISTRO O AL ACCESO NO AUTORIZADO AL MISMO, YA SEA DEBIDO A INCUMPLIMIENTO CONTRACTUAL, ILÍCITO PENAL O NEGLIGENCIA, O A CUALQUIER OTRA CAUSA. LAS DESCARGAS DE MATERIALES O SU OBTENCIÓN POR OTROS MEDIOS A TRAVÉS DEL USO DE LOS SERVICIOS SON POR CUENTA Y RIESGO DEL USUARIO, SOBRE QUIEN RECAERÁ ÍNTEGRAMENTE LA RESPONSABILIDAD POR CUALESQUIERA DAÑOS EN SU SISTEMA INFORMÁTICO O POR PÉRDIDAS DE DATOS QUE SE DERIVEN DE LA DESCARGA DE DICHOS MATERIALES. NINGUNA INFORMACIÓN O RECOMENDACIÓN, VERBAL O ESCRITA, QUE EL USUARIO HAYA RECIBIDO DE ROLAND A TRAVÉS DEL SERVICIO DARÁ LUGAR AL ESTABLECIMIENTO DE GARANTÍAS QUE NO SEAN LAS EXPRESAMENTE INDICADAS EN ESTAS CONDICIONES GENERALES.</p>

<hr />

<h4>Limitación de responsabilidad:</h4>
<p>NI ROLAND NI NINGUNO DE SUS EMPLEADOS, AGENTES, SUCESORES, CESIONARIOS, EMPRESAS ASOCIADAS O PROVEEDORES DE CONTENIDOS O SERVICIOS SERÁN RESPONSABLES ANTE USTED O ANTE TERCEROS POR CUALESQUIERA DAÑOS DIRECTOS, INDIRECTOS, INCIDENTALES, ESPECIALES, EMERGENTES O PUNITIVOS; INCLUIDOS, CON CARÁCTER NO EXHAUSTIVO, DAÑOS POR LUCRO CESANTE, PÉRDIDA DE REPUTACIÓN COMERCIAL, USO, DAÑOS QUE AFECTEN A DATOS U OTROS DAÑOS INTANGIBLES (INCLUSO EN EL CASO DE QUE ROLAND HUBIESE SIDO ADVERTIDA DE LA POSIBILIDAD DE OCURRENCIA DE TALES DAÑOS), QUE VENGAN OCASIONADOS POR (i) EL USO QUE USTED HAGA DEL SERVICIO, (ii) LA IMPOSIBILIDAD DE ACCEDER AL SERVICIO O HACER USO DEL MISMO, (iii) EL COSTE DE ADQUIRIR O SUSTITUIR BIENES Y SERVICIOS POR CAUSA DE BIENES, DATOS, INFORMACIÓN O SERVICIOS ADQUIRIDOS U OBTENIDOS A TRAVÉS DEL SERVICIO, O DE MENSAJES RECIBIDOS O TRANSACCIONES REALIZADAS MEDIANTE EL MISMO, (iv) EL ACCESO NO AUTORIZADO A SUS TRANSMISIONES O DATOS O MODIFICACIÓN DE LOS MISMOS, (v) DECLARACIONES FORMALES O ACTOS DE ROLAND O DE TERCEROS RELATIVOS AL SERVICIO, O QUE (vi) NO GUARDEN RELACIÓN CON EL INCUMPLIMIENTO DE ALGUNA GARANTÍA.</p>

<hr />

<h4>Uso del Servicio por el Usuario:</h4>
<p>Su capacidad para utilizar el Servicio está sujeta al cumplimiento en todo momento de la totalidad de las Condiciones Generales. Salvo que en el Sitio Web se disponga lo contrario, Nosotros no otorgamos a su favor licencia alguna sobre los contenidos, funciones o materiales a los que pueda acceder a través del Servicio; entre ellos, a título meramente enunciativo, marcas comerciales, marcas comerciales registradas, marcas de servicio, materiales que puedan estar sujetos a derechos de autor, o propiedad intelectual de cualquier clase incluida en el Servicio. Salvo que en el Sitio Web se disponga otra cosa, Usted no podrá, independientemente de la finalidad que persiga, descargar o guardar una copia de las pantallas o del “contenido” del Servicio (incluida información, datos, software, fotografías, gráficos y cualesquiera otros materiales, independientemente del formato en el que se hallen), ni modificarlos parcial o totalmente, salvo que en estas Condiciones Generales se disponga otra cosa. Sí podrá, no obstante, imprimir una copia del contenido de este Sitio Web para su uso personal o para sus registros, así como acceder al Servicio a través de un ordenador individual, siempre que, tanto Usted como los terceros autorizados por Usted, se abstengan de (i) distribuir, copiar, modificar, desensamblar, aplicar operaciones de ingeniería inversa o tratar por cualquier otro medio de obtener el código fuente, el contenido o cualquier parte del Servicio, o desarrollar trabajos derivados a partir de estos, o de (ii) vender, arrendar, prestar, ceder, otorgar una sublicencia o establecer derechos de garantía sobre el contenido del Servicio o transmitir por cualquier otro medio derechos sobre el mismo.</p>

<hr />

<h4>Requisitos para el registro:</h4>
<p>Se le podrá pedir que se registre para darle acceso a ciertas partes del Servicio. Para registrarse y mantener su condición de usuario registrado, deberá facilitar y actualizar cuando sea necesario la información de registro que se le solicite, la cual habrá de ser en todo momento precisa, completa y veraz, además de actualizada. En caso de que tengamos razones fundadas para suponer que su información de registro no esté puesta al día o no sea precisa, completa y veraz, nos reservamos el derecho a interrumpir o dar por terminado sin previo aviso su acceso al Servicio, incluyendo el acceso a la información que Usted pudiera tener almacenada en el mismo.</p>

<hr />

<h4>Derechos propietarios:</h4>
<p>Tanto el Servicio como el software utilizado en él contienen información confidencial y sujeta a derechos de propiedad, que se halla amparada por las leyes de protección de la propiedad intelectual y otras y que usted no podrá usar ilícitamente ni de ninguna manera que no esté expresamente autorizada en estas Condiciones Generales. Salvo disposición en contrario, Roland es propietaria y/o usuaria autorizada de todas las marcas comerciales, marcas comerciales registradas y/o marcas de servicio que figuran en el Servicio, así como titular de los derechos de autor o licenciataria de los contenidos y/o la información del Sitio Web. El uso por parte de Usted de este Sitio Web de alguna manera que no esté expresamente autorizada en estas Condiciones Generales puede suponer una infracción de la legislación que ampara los derechos de autor y de otras leyes de Japón y/u otros países. El uso que Nosotros hagamos de las marcas comerciales, marcas comerciales registradas, marcas de servicio, materiales que puedan estar sujetos a derechos de autor, o propiedad intelectual de cualquier clase que se encuentre en este Sitio Web no le confiere a Usted derechos de licencia de ninguna clase ni autorización de ningún otro tipo sobre dichas marcas y materiales.</p>

<hr />

<h4>Contenido suministrado por terceros:</h4>
<p>Cierta información contenida en este Sitio Web, así como materiales de referencia o enlaces a otros sitios se facilitan únicamente a efectos de información general y no podrán ser invocados como base de referencia para cualquier finalidad. A este respecto, Roland y sus proveedores de datos y de contenidos declinan toda responsabilidad por errores o demoras en el contenido o por cualesquiera actos que se realicen tomando este como referencia, no garantizando Roland la exactitud, veracidad e integridad de dicho contenido.</p>
<p>Usted admite, asimismo, la posibilidad de que al hacer uso del Servicio acceda a contenidos que podría considerar injuriosos, obscenos u ofensivos. Es su responsabilidad evaluar, valorar y sopesar los riesgos asociados al uso de dichos contenidos. En este sentido, Roland declina toda responsabilidad por los contenidos; incluyendo, a título meramente enunciativo, posibles errores u omisiones en los mismos o daños, pérdidas o lesiones de cualquier tipo que pudieran derivarse del uso que Usted o terceras partes hagan del contenido distribuido mediante el Servicio o al que se haya accedido de cualquier otra forma a través de este.</p>

<hr />

<h4>Utilización del Servicio por el Usuario:</h4>
<p>Usted reconoce y acepta su deber de: (a) disponer de acceso propio a la World Wide Web y pagar las cuotas correspondientes a los servicios de acceso, y de (b) disponer del equipo necesario para conectarse a la World Wide Web; equipo que comprenderá al menos un ordenador, software, un módem y una línea telefónica operativa.</p>
<p>Al hacer uso del Servicio, usted deberá abstenerse de:</p>
<ol>
<li>cargar, compartir, publicar, transmitir, reproducir, enviar por correo electrónico o distribuir por cualquier medio contenidos obtenidos a través del Servicio que estén amparados por derechos de autor u otros derechos de propiedad intelectual, así como trabajos derivados de dichos contenidos, salvo que disponga de autorización expresa y por escrito de Roland y del titular de los derechos de autor, las marcas comerciales, las patentes u otros derechos;</li>
<li>cargar, compartir, publicar, reproducir, enviar por correo electrónico, transmitir o distribuir por cualquier medio contenidos sobre los cuales no ostente derecho a exhibir o transmitir en virtud de disposición legal o de relaciones contractuales o fiduciarias; </li>
<li>cargar, compartir, publicar, reproducir, transmitir, enviar por correo electrónico o distribuir por cualquier medio componentes del propio Servicio o trabajos derivados de estos, puesto que el Servicio, en tanto que trabajo colectivo, se halla amparado por derechos de autor en virtud de la legislación japonesa en la materia; </li>
<li>cargar, compartir, publicar, reproducir, enviar por correo electrónico, transmitir o distribuir por cualquier medio a través del Servicio contenidos que infrinjan derechos de patente, marcas comerciales, secretos comerciales, derechos de autor u otros derechos propietarios de alguna de las partes; </li>
<li> cargar, compartir, publicar o transmitir a través del Servicio información ilícita, fraudulenta, injuriosa, difamatoria, obscena, pornográfica, blasfema, intimidatoria, insultante, falsa, constitutiva de acoso, torticera, soez, invasiva (de la intimidad de otros), ominosa o racial o étnicamente ofensiva de cualquier clase; incluidas, sin ánimo exhaustivo, las transmisiones que impliquen o que fomenten comportamientos susceptibles de constituir actividades ilegales o delitos, que den lugar al nacimiento de responsabilidad civil o que infrinjan de cualquier otra manera las leyes locales, estatales, nacionales o extranjeras;</li>
<li>cargar, compartir, publicar, transmitir, reproducir, enviar por correo electrónico, distribuir o explotar comercialmente por cualquier medio contenidos obtenidos a través del Servicio, salvo para aquellos fines que expresamente autorice el proveedor de dichos contenidos; </li>
<li>limitar, obstaculizar o restringir el uso y disfrute del Servicio por otros usuarios; </li>
<li>publicar o transmitir anuncios, ofertas de servicios, cadenas de cartas, planes piramidales, oportunidades o planes de inversión u otras comunicaciones comerciales no solicitadas, salvo en aquellos casos expresamente autorizados por el Servicio, o incurrir en prácticas de “spamming” o “flooding”; </li>
<li>suplantar la identidad de otra persona física o jurídica, o facilitar datos personales que inciten a confundir su identidad con la de otra persona física o jurídica; </li>
<li>publicar o transmitir en el Servicio cualquier información, aplicación o programa informático que contenga virus, troyanos, gusanos u otros componentes dañinos; </li>
<li>causar daño de cualquier modo a menores de edad; </li>
<li>incorporar encabezados falsos o manipular identificadores a fin de ocultar el origen de contenidos transmitidos a través del Servicio; </li>
<li>recabar o almacenar para cualquier fin datos personales de otros usuarios; o</li>
<li>infringir, intencionadamente o no, cualquier ley local, estatal, nacional o internacional vigente.</li>
</ol>

<hr />

<h4>Contenido accesible:</h4>
<p>Usted reconoce y acepta que la parte que publica cada contenido individual al que se puede acceder a través del Servicio es responsable exclusiva de ese contenido. Es decir, que es Usted, y no Roland, el único responsable de todo el contenido que cargue, publique, envíe por correo electrónico, transmita o distribuya de cualquier otra forma a través del Servicio. Asimismo, Roland declina toda responsabilidad con respecto a contenidos que Usted reciba de terceras partes que carguen, publiquen, envíen por correo electrónico, transmitan o distribuyan de cualquier otra forma dichos contenidos a través del Servicio.</p>
<p>Roland no analiza previamente ni está obligada a controlar el contenido que Usted o una tercera parte publiquen en el Servicio. No obstante, Usted reconoce y acepta que nos reservamos el derecho de controlar el Servicio a nuestra absoluta discreción y de suprimir o cambiar cualquier contenido al que pueda accederse a través del Servicio. Nos reservamos, asimismo, la facultad de revelar cualquier información cuando así lo consideremos necesario para cumplir con la normativa vigente u otras exigencias administrativas, para garantizar un adecuado funcionamiento del Servicio o para proteger a Roland, a sus clientes o a los usuarios del Sitio Web. Sin perjuicio de lo anterior, y salvo disposición legal en contrario, nos abstendremos de controlar o revelar intencionadamente mensajes privados de correo electrónico que usted dirija única y específicamente a Roland. Nos reservamos el derecho de rechazar la publicación o retirar parte o la totalidad de informaciones y materiales que a nuestra absoluta discreción consideremos inaceptables, inadecuados, indeseables o contrarios a estas Condiciones Generales.</p>

<hr />

<h4>Uso de los datos enviados:</h4>
<p>Todas las informaciones y contenidos publicados a través del Servicio; entre ellos y a título meramente enunciativo, contenidos que se publiquen en los tableros de mensajes del Sitio Web, se considerarán ahora y en el futuro propiedad de Roland. A este respecto, Roland podrá utilizar libremente para cualquier finalidad (incluida la explotación comercial) las ideas, conceptos, conocimientos especializados y técnicas comprendidas en las informaciones y contenidos que cualquier usuario ponga a disposición del público a través de este Sitio Web, sin que Roland quede obligada por deber alguno de confidencialidad con respecto a la información publicada, salvo disposición legal o pacto en contrario.</p>

<hr />

<h4>Enlaces contenidos en el Servicio o que dirijan a él:</h4>
<p>Usted reconoce y acepta que tanto Roland como los proveedores que comparten marcas en su Sitio Web declinan toda responsabilidad relativa a la exactitud o la disponibilidad de la información proporcionada (en su caso) por sitios web a los que se acceda desde enlaces contenidos en este Sitio Web. Los enlaces a sitios web externos no implican que Roland o los proveedores que comparten marcas en su Sitio Web apoyen a los patrocinadores de tales sitios ni aprueben los contenidos, productos, anuncios u otros materiales ofrecidos en ellos. Roland no es responsable tampoco de la creación, edición o control de dichas páginas o enlaces. A este respecto, Usted reconoce y acepta que Roland no es responsable ni imputable, directa o indirectamente, de cualquier daño o pérdida ocasionado real o presuntamente por el uso que Usted haga o por la confianza que Usted haya depositado en los contenidos, bienes o servicios ofrecidos en dichos sitios web o recursos externos, o en relación con los mismos.</p>

<hr />

<h4>Incumplimiento y extinción de las Condiciones Generales:</h4>
<p>Usted reconoce y acepta que podamos denegarle sin previo aviso el acceso a parte o la totalidad del Servicio en el caso de que Usted participe en comportamientos o actividades que Nosotros consideremos, a nuestra absoluta discreción, que violan cualquiera de las presentes Condiciones Generales, infringen los derechos de Roland o son inapropiados por cualquier otro motivo para permitirle un acceso continuado.</p>
<p>En este sentido, usted acuerda defender y mantener indemne a Roland y a sus filiales contra cualesquiera demandas, responsabilidades, costas y gastos, incluidos gastos razonables de asesoría legal, que pudieran derivarse del uso que Usted haga del Servicio o de la publicación o transmisión de mensajes, informaciones, software u otros materiales a través del Servicio realizada por Usted o por usuarios de su cuenta, o que guarden relación con cualquier infracción de estas Condiciones Generales por parte de Usted o de usuarios de su cuenta.</p>

<hr />

<h4>Generalidades:</h4>
<p>Nos reservamos el derecho a modificar sin previo aviso cualquier información contenida en este Sitio Web; incluida, sin ánimo exhaustivo, la suspensión del Servicio o la revisión y/o supresión de funcionalidades u otra información del Sitio Web. Algunos de los enlaces contenidos en este Sitio Web le darán acceso (en su caso) a sitios web de terceros sobre cuyos contenidos, accesibilidad u otras cuestiones no asumimos responsabilidad de ningún tipo. (Véase el apartado “Enlaces contenidos en el Servicio o que dirijan a él” anterior). El contenido de este Sitio Web podrá también variar dependiendo de la configuración y las limitaciones de su navegador.</p>
<p>Tanto Usted como Roland acuerdan someterse a la jurisdicción exclusiva y personal de los tribunales de Osaka (Japón). Las presentes Condiciones Generales y la relación jurídica establecida entre Usted y Roland se regirá por la legislación de Japón, sin perjuicio de lo que la legislación de este país establezca en relación con el conflicto de leyes. Sin perjuicio de lo anterior, Usted se compromete a observar íntegramente la normativa local de cualquier jurisdicción, incluidas las jurisdicciones no japonesas, en lo referente a comportamientos en la Red y al uso de información personal. Usted asimismo acuerda observar íntegramente la legislación vigente en materia de transmisión de datos exportados del país en el que tenga su residencia y desde el cual Usted acceda al Servicio.</p>
<p>La incapacidad de Roland para ejercer o hacer cumplir alguno de los derechos o disposiciones de estas Condiciones Generales no constituirá renuncia por su parte a tales derechos o disposiciones. En caso de que un tribunal competente dictase la invalidez de alguna de las disposiciones de las presentes Condiciones Generales, las partes acuerdan sugerir al tribunal que haga lo posible por respetar la vigencia de las intenciones de las partes según se desprenda de la disposición en cuestión, manteniendo el resto de disposiciones de estas Condiciones Generales su plena vigencia y desplegando todos sus efectos.</p>
<p>Todas las razones sociales, nombres de productos y marcas de logotipos que se mencionan en este Sitio Web son marcas comerciales registradas o marcas comerciales de Roland Corporation o de sus respectivos titulares.</p>

</div>
</section>